# Generated by Django 3.1.7 on 2021-05-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210526_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_created',
        ),
    ]
