# Generated by Django 3.1.7 on 2021-05-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinfo_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_created',
        ),
    ]
