# Generated by Django 3.1.7 on 2021-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userinfo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
