# Generated by Django 3.2.3 on 2021-06-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinfo_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=1000)),
                ('singer_name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='documents/')),
                ('movie', models.CharField(default='', max_length=1000)),
                ('song', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
