# Generated by Django 3.2 on 2021-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_song_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='Geet/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='Geet/'),
        ),
    ]
