# Generated by Django 3.2 on 2021-06-14 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlater',
            new_name='Listenlater',
        ),
    ]
