# Generated by Django 3.2 on 2021-07-10 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_watchlater_listenlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='done_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
