# Generated by Django 3.2 on 2021-07-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_watch_id_listenlater_listen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenlater',
            old_name='video_id',
            new_name='later_id',
        ),
    ]
