# Generated by Django 3.2.3 on 2021-07-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_comment'),
        ('accounts', '0017_listenlater_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.postmodel'),
        ),
    ]
