# Generated by Django 3.2.3 on 2021-07-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_song_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='post',
        ),
    ]
