# Generated by Django 3.2.3 on 2021-07-02 07:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_postmodel_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postmodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
