# Generated by Django 3.2.3 on 2021-07-05 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_postmodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, unique=True),
        ),
    ]
